[package]
name = "upkg"
version = "0.1.0"
edition = "2024"

[dependencies]
mlua = {version = "0.11.1", features = ["luau", "vendored", "macros", "serde"]}
serde = {version = "1.0", features = ["derive"]}
strum = {version = "0.27", features = ["derive"]}
